ground_floor:
  - id: "G1"
    is_tv: false
    is_ac: true
  - id: "G2"
    is_tv: false
    is_ac: true
  - id: "G3"
    is_tv: false
    is_ac: true
  - id: "G4"
    is_tv: false
    is_ac: true
  - id: "G5"
    is_tv: false
    is_ac: true
  - id: "G6"
    is_tv: false
    is_ac: true
  - id: "G7"
    is_tv: false
    is_ac: true

first_floor:
  - id: "101"
    is_tv: false
    is_ac: true
  - id: "102"
    is_tv: false
    is_ac: true
  - id: "103"
    is_tv: true
    is_ac: true
  - id: "104"
    is_tv: false
    is_ac: true
  - id: "105"
    is_tv: false
    is_ac: true
  - id: "106"
    is_tv: true
    is_ac: true
  - id: "107"
    is_tv: true
    is_ac: true
  - id: "108"
    is_tv: false
    is_ac: true
  - id: "109"
    is_tv: false
    is_ac: true
  - id: "110"
    is_tv: false
    is_ac: true
  - id: "111"
    is_tv: false
    is_ac: true
  - id: "112"
    is_tv: false
    is_ac: true
  - id: "113"
    is_tv: false
    is_ac: true

second_floor:
  - id: "201"
    is_tv: false
    is_ac: true
  - id: "202"
    is_tv: false
    is_ac: true
  - id: "203"
    is_tv: false
    is_ac: true
  - id: "204"
    is_tv: false
    is_ac: true
  - id: "205"
    is_tv: false
    is_ac: true
  - id: "206"
    is_tv: false
    is_ac: true
  - id: "207"
    is_tv: false
    is_ac: true
  - id: "208"
    is_tv: false
    is_ac: true
  - id: "209"
    is_tv: false
    is_ac: true
  - id: "210"
    is_tv: false
    is_ac: true
  - id: "211"
    is_tv: false
    is_ac: true
  - id: "212"
    is_tv: false
    is_ac: true
  - id: "213"
    is_tv: false
    is_ac: true
  - id: "214"
    is_tv: false
    is_ac: true
  - id: "215"
    is_tv: false
    is_ac: true
